"""add description for topic

Revision ID: 648faaf68173
Revises: 
Create Date: 2020-04-24 14:52:43.483482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648faaf68173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('subtopics', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('topics', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'description')
    op.drop_column('subtopics', 'description')
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###
