"""like-dislike v3

Revision ID: 94eefa511bb6
Revises: bbc868f47c2c
Create Date: 2020-04-24 22:23:18.400576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94eefa511bb6'
down_revision = 'bbc868f47c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dislike', type_='foreignkey')
    op.create_foreign_key(None, 'dislike', 'comments', ['disliked'], ['id'])
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'comments', ['liked'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'users', ['liked'], ['id'])
    op.drop_constraint(None, 'dislike', type_='foreignkey')
    op.create_foreign_key(None, 'dislike', 'users', ['disliked'], ['id'])
    # ### end Alembic commands ###
