"""like-dislike

Revision ID: 9ed4d5ec69d8
Revises: c0ff56715f93
Create Date: 2020-04-24 21:48:41.435185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed4d5ec69d8'
down_revision = 'c0ff56715f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('liker', sa.INTEGER(), nullable=True),
    sa.Column('liked', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['liked'], ['users.id'], ),
    sa.ForeignKeyConstraint(['liker'], ['users.id'], )
    )
    # ### end Alembic commands ###
