"""like v2 update

Revision ID: bbc868f47c2c
Revises: 9ed4d5ec69d8
Create Date: 2020-04-24 22:11:39.639250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc868f47c2c'
down_revision = '9ed4d5ec69d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
